### ISSUE TITLE
A suggestion 🙂

### ISSUE THREAD

**Issue by usser1976** [Eris11dib/RandomWords#2]
This is a really great plugin 🤗 
Would it be possible to add a function that the player who won has to expose a round?  
Otherwise it is possible that always wins the same who plays on the pc 🤔

**Comment by Eris11dib** [comment]
Thank for the suggestion, i will start coding this feature in the next days

**Comment by usser1976** [comment]
That would be great, we have a player who always wins and the others have no fun.

**Comment by Eris11dib** [comment]
Here we go, i added this feature,enjoy

**Comment by usser1976** [comment]
Thanks, your plugin is already running on our server.  It's fun for everyone 🤗
